force-app/main/default/objects/Affiliated_Contact__c/Affiliated_Contact__c.object-meta.xml
<CustomObject>
    <label>Affiliated Contact</label>
    <nameField>
        <displayFormat>AFC-{00000}</displayFormat>
        <label>Affiliated Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliated Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliated_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affiliated_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FetchAffiliated.cls
global with sharing class FetchAffiliated {
@auraEnabled
    public static List<Affiliated_Contact__c> getAllaffiliatedcontacts()
    {
     List<Affiliated_Contact__c> acontact=new LIST<Affiliated_Contact__c>();
        acontact=[select id,First_Name__c,Last_Name__c,Email__c from Affiliated_Contact__c];
        return acontact;
    }
    public Affiliated_Contact__c getSelectedaffiliatedcontacts(Id id)
    {
      Affiliated_Contact__c acontact=[select id,First_Name__c,Last_Name__c,Email__c from Affiliated_Contact__c where id=:id];
        return acontact;
    }

}